-- Incident persistence. An incident is opened when the inference service
-- reports an alerting detection on a camera, and updated as more frames
-- corroborate it. Redis caches the open-incident state per camera; this table
-- is the durable system of record.

CREATE TABLE incidents (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    camera_id       TEXT        NOT NULL,
    camera_name     TEXT        NOT NULL,
    label           TEXT        NOT NULL,
    max_confidence  REAL        NOT NULL,
    status          TEXT        NOT NULL DEFAULT 'OPEN',  -- OPEN | RESOLVED
    detection_count INTEGER     NOT NULL DEFAULT 1,
    first_frame_id  BIGINT      NOT NULL,
    last_frame_id   BIGINT      NOT NULL,
    opened_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at     TIMESTAMPTZ
);

CREATE INDEX idx_incidents_camera_status ON incidents (camera_id, status);
CREATE INDEX idx_incidents_opened_at     ON incidents (opened_at DESC);
